= Ruby on Rails
:lab: 8

== Задание

Разработать веб-приложение, имеющее HTML-страницу с формой ввода данных и HTML-страницу для представления результатов.
Результат расчёта должен быть представлен в форме таблицы, оформленной с помощью элемента table или отдельными ячейками div и имеющей не менее двух колонок.
Если по условию задания результат может быть представлен только в виде одной строки таблицы, необходимо реализовать вывод промежуточных результатов расчёта в качестве дополнительных строк.
В этом случае первой колонкой таблицы будет порядковый номер итерации.

Под вводом с клавиатуры в тексте заданий следует понимать ввод в поле ввода данных формы на HTML-странице.

=== Текст задания

Написать программу, определяющую, сколько из чисел в диапазоне от 0 до n (n вводится с клавиатуры), сами являясь палиндромами, при возведении в квадрат, образуют палиндромы.
Например: 22 ^2^ → 484 . Вывести на печать числа, квадраты и их количество.

== Результат

.app/controllers/welcome_controller.rb
[source,ruby]
----
include::app/controllers/welcome_controller.rb[]
----

.app/views/welcome/result.html.erb
[source,erb]
----
include::app/views/welcome/result.html.erb[]
----

.app/views/welcome/index.html.erb
[source,erb]
----
include::app/views/welcome/index.html.erb[]
----

.test/controllers/welcome_controller_test.rb
[source,ruby]
----
include::test/controllers/welcome_controller_test.rb[]
----

.config/routes.rb
[source,ruby]
----
include::config/routes.rb[]
----
