= Добавление модели. ORM. Разработка БД, подключение, хранение и поиск данных
:lab: 11

Модифицировать код ЛР 8 таким образом, чтобы запросы, которые были ранее выполнены, сохранялись в БД и при следующем запросе не требовали повтора вычислений.

- Сформировать модель в соответствии с потребностями хранения данных. Входные параметры являются ключами, по которым извлекается результат.

- Выполнить создание БД и миграцию соответствующими запросами rake.

- Написать тест на добавление и поиск данных с помощью модели. Проверить выполнение теста.

- Модифицировать код приложения таким образом, чтобы результат вычислений преобразовывался в строковый или бинарный формат (на выбор: json, xml, и пр.). Проверить через отладочную печать в консоль, что преобразование выполняется корректно.

- Вставить код для сохранения данных в БД и запрос на поиск предыдущего результата вычислений.

- Добавить действие в контроллер, позволяющее определить, что хранится в БД через сериализацию в XML.

- Проверить, что при выполнении запроса, данные добавляются в БД.

- При помощи консоли сообщений Webrick определить, производится ли поиск результата предыдущего запроса в БД и не повторяются ли одни и те же вычисления.

- Модифицировать модель таким образом, чтобы добавление записей с одинаковыми параметрами было невозможно.

- Реализовать тест модели, проверяющий невозможность повторного добавления одних и тех же результатов вычислений.

- Реализовать функциональный тест, проверяющий, что результаты вычислений различны при различных входных параметрах.

- Проверить маршруты приложения с помощью rake routes и убрать лишние. Обеспечить доступ при обращении по адресу `/`.


== Модель
В качестве строкового формата хранения данных был выбран https://en.wikipedia.org/wiki/Bencode[Bencode].

.app/models/cached_result.rb
[source,ruby]
----
include::app/models/cached_result.rb[]
----

.db/migrate/20201129200943_create_cached_results.rb
[source,ruby]
----
include::db/migrate/20201129200943_create_cached_results.rb[]
----

.db/schema.rb
[source,ruby]
----
include::db/schema.rb[]
----

.test/models/cached_result_test.rb
[source,ruby]
----
include::test/models/cached_result_test.rb[]
----

.test/fixtures/cached_results.yml
[source,yaml]
----
include::test/fixtures/cached_results.yml[]
----

== Контроллер

.app/controllers/welcome_controller.rb
[source,ruby]
----
include::app/controllers/welcome_controller.rb[]
----

.test/controllers/welcome_controller_test.rb
[source,ruby]
----
include::test/controllers/welcome_controller_test.rb[]
----

.config/routes.rb
[source,ruby]
----
include::config/routes.rb[]
----



== SQL консоль

.Поиск предыдущего значения
[source, sql]
----
SELECT "cached_results".* FROM "cached_results" WHERE "cached_results"."n" = ? LIMIT ?
----

.Проверка N на уникальность методом `#validate`
[source, sql]
----
SELECT 1 AS one FROM "cached_results" WHERE "cached_results"."n" = ? LIMIT ?
----

.Вставка нового значения
[source, sql]
----
INSERT INTO "cached_results" ("n", "result", "created_at", "updated_at") VALUES (?, ?, ?, ?)
----

.Состояние БД
[source, xml]
----
include::cached.xml[]
----
